import { RiShieldUserFill, RiLoginCircleLine } from "react-icons/ri";
import { FaPersonSnowboarding, FaCircleUser } from "react-icons/fa6";
import { PiDotsThreeOutlineDuotone } from "react-icons/pi";
import { TiHome } from "react-icons/ti";
import { HiMail } from "react-icons/hi";
import { BsFillShieldLockFill } from "react-icons/bs";
import { IoEye, IoEyeOff } from "react-icons/io5";
import { FaSnowboarding } from "react-icons/fa";

export const Register = RiShieldUserFill;
export const Login = RiLoginCircleLine;
export const StartNow = FaPersonSnowboarding;
export const ThreeDots = PiDotsThreeOutlineDuotone;
export const Home = TiHome;
export const User = FaCircleUser;
export const Email = HiMail;
export const Password = BsFillShieldLockFill;
export const Eye = IoEye;
export const EyeOff = IoEyeOff;
export const Logout = FaSnowboarding;
